_default:
    vcs: git
    prerequisites: [working-copy-check]
    version-generator: simple
    version-persister:
        name: vcs-tag
        tag-prefix: "{branch-name}_"
    post-release-actions:
        vcs-publish: ~
        vendor/phbergsmann/typo3-repository-client-rmt-bridge/src/TYPO3ExtensionUploader.php: ~

master:
    prerequisites: [working-copy-check, display-last-changes]
    pre-release-actions:
        changelog-update:
            format: semantic
            file: CHANGELOG.md
            dump-commits: true
        vendor/phbergsmann/typo3-repository-client-rmt-bridge/src/TYPO3ExtensionVersioner.php: ~
        vcs-commit: ~
    version-generator: semantic
    version-persister: vcs-tag